### ISSUE TITLE
Add shields to README

### ISSUE THREAD

**Issue by mahi-pas** [open-horizon-services/SmartAg-foundation#6]
See https://github.com/open-horizon-services/service-homeassistant for an example of shields to add

**Comment by julianchen215** [comment]
Hi @mahi-pas, can you please assign this to me?

**Comment by joewxboy** [comment]
Also, consider adding the "Contributor" shield - example in https://github.com/open-horizon-services/service-node-red-hello-world

**Comment by joewxboy** [comment]
@julianchen215 You have it!  Let me know if you have any questions.
